const os = require('os');
console.log(os.platform());
console.log(os.arch());
console.log(os.type());
console.log(os.release());
console.log(os.userInfo());
console.log(os.homedir());
console.log(os.cpus());
console.log(os.freemem());
console.log(os.uptime());